/// <reference types="vite/client" />
declare let LazyLoad: any;
declare let GLightbox: any;
declare let gsap: any;
declare let Swiper: any;
declare let echarts: any;
declare let IMask: any;
declare let Handlebars: any;
declare let Choices: any;
declare let rangeSlider: any;
declare let Toastify: any;
declare let FloatingUIDOM: any;
